baseURL = 'https://lyvykhang.github.io/'
locale = 'en-us'
title = 'Academic CV'
theme = 'xmin'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
  name = 'About'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'Research'
  url = '/research/'
  weight = 2

[[menu.main]]
  name = 'CV'
  url = '/cv/cv-placeholder.pdf'
  weight = 3